apiVersion: v1
kind: Service
metadata:
  name: svc-app-webcolor-blue
  labels:
    app: app-webcolor-blue
spec:
  type: ClusterIP
  selector:
    app: app-webcolor-blue
  ports:
    - port: 9000
      targetPort: 9000